# Generated by Django 5.2 on 2025-06-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Categoria_Servicio',
            fields=[
                ('id_categoria_servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_servicio', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Categoria Servicio',
                'verbose_name_plural': 'Categoria Servicios',
                'db_table': 'Categoria Servicio',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(verbose_name='Fecha De Compra')),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de Compra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=2, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Comprobante_Pago',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comprobante', models.DateField()),
                ('codigo_comprobante', models.CharField(max_length=20, verbose_name='Codigo De Comprobante')),
                ('estado_comprobante', models.CharField(max_length=2, verbose_name='Estado Comprobante')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.compra')),
            ],
            options={
                'verbose_name': 'Comprobante Pago',
                'verbose_name_plural': 'Comprobante Pagos',
                'db_table': 'Comprobante Pago',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion_producto', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('imagen_producto', models.ImageField(blank=True, upload_to='', verbose_name='Imagen Producto')),
                ('cantidad_maxima', models.IntegerField(verbose_name='Cantidad Maxina')),
                ('cantidad_minima', models.IntegerField(verbose_name='Cantidad Minima')),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('existencia_prodcuto', models.IntegerField(verbose_name='Existencia')),
                ('tipo_producto', models.IntegerField(verbose_name='Tipo Producto')),
                ('producto_activo', models.BooleanField(verbose_name='Producto Activo')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Compra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto_compra', models.IntegerField(verbose_name='Cantidad Productos')),
                ('precio_unitario_compra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Unitario')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.producto')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalles Compras',
                'db_table': 'Detalle Compra',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('estado_servicio', models.CharField(max_length=2, verbose_name='Estado Servicio')),
                ('fecha_servicio', models.DateField(verbose_name='Fecha Pedido')),
                ('comentario_servicio', models.CharField(max_length=150)),
                ('id_categoria_servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.categoria_servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Servicio',
            fields=[
                ('id_detalle_servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto_servicio', models.IntegerField(verbose_name='Cantidad Productos')),
                ('precio_unitario_servicio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Unitario')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.producto')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.servicio')),
            ],
            options={
                'verbose_name': 'Detalle Servicio',
                'verbose_name_plural': 'Destalle Servicios',
                'db_table': 'Detalle Servicio',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_usuario', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo_usuario', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('password_usuario', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('telefono_usuario', models.CharField(max_length=10, verbose_name='Telefono')),
                ('imagen_usuario', models.ImageField(blank=True, upload_to='', verbose_name='Imagen Usuario')),
                ('usuario_activo', models.BooleanField(verbose_name='Cuenta Activa')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_comentario', models.CharField(max_length=50, verbose_name='Titulo')),
                ('comentario', models.CharField(max_length=200, verbose_name='Comentario')),
                ('fecha_comentario', models.DateField(verbose_name='Fecha')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'Comentario',
            },
        ),
    ]
