# Generated by Django 5.2 on 2025-06-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password_usuario',
            field=models.CharField(max_length=150, verbose_name='Contraseña'),
        ),
    ]
