# Generated by Django 5.2 on 2025-06-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_password_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='existencia_prodcuto',
            new_name='existencia_producto',
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado_categoria',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='categoria_servicio',
            name='estado_categoria_servicio',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
