# Generated by Django 5.2 on 2025-06-23 15:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_existencia_prodcuto_producto_existencia_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_usuario',
            field=models.ImageField(blank=True, upload_to=app.models.ruta_unica, verbose_name='Imagen Usuario'),
        ),
    ]
