# Generated by Django 5.2 on 2025-06-24 00:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuario_imagen_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, upload_to=app.models.ruta_unica, verbose_name='Imagen Producto'),
        ),
    ]
