# Generated by Django 5.2 on 2025-08-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.IntegerField(choices=[(1, 'Arreglo Flores'), (2, 'Arreglo Personalizado'), (3, 'Arreglo Mixto')], verbose_name='Tipo Producto'),
        ),
    ]
