# Generated by Django 5.2 on 2025-11-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_tipo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_servicio',
            name='id_producto',
        ),
    ]
