# Generated by Django 5.2 on 2025-11-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_detalle_servicio_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_servicio',
            name='total_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='cantidad_servicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
